#!/bin/bash
#Script by Malayaacx01 - Shop | Ajis - Shop 2024
echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
echo -e "${BIBlue}│ ${BGCOLOR}          DOWNLOAD AUTOSCRIPT - CRONTAB BY MALAYAACX01           ${NC}${BIBlue} │${NC}"
echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
sudo echo -e "0 4 * * * root helium_daily # Helium by Abi Darwish" >>/etc/crontab
sudo echo -e "0 0 * * * root warp o && sleep 5 && wget -N scvpsv2.malayaacx.my.id/auto-scriptrestart.sh && chmod +x auto-scriptrestart.sh && bash auto-scriptrestart.sh && rm -rf auto-scriptrestart.sh # Autoscript Restart - By Malayaacx01" >>/etc/crontab
sudo echo -e "10 0 * * * root warp o && sleep 5 && wget -N scvpsv2.malayaacx.my.id/clearram-autoscript.sh && chmod +x clearram-autoscript.sh && bash clearram-autoscript.sh && bash warp o && rm -rf clearram-autoscript.sh # Autoscript Restart - By Malayaacx01" >>/etc/crontab
sudo echo -e "15 0 * * * root systemctl disable dnsmasq >/dev/null 2>&1 && systemctl stop dnsmasq && echo "nameserver 1.1.1.1" >/etc/resolv.conf && systemctl enable dnsmasq >/dev/null 2>&1 && systemctl restart dnsmasq && echo "nameserver 127.0.0.1" >/etc/resolv.conf # Autoscript Restart - By Malayaacx01" >>/etc/crontab
sudo echo -e "0 6 * * * root warp o && sleep 5 && wget -N scvpsv2.malayaacx.my.id/auto-scriptrestart.sh && chmod +x auto-scriptrestart.sh && bash auto-scriptrestart.sh && rm -rf auto-scriptrestart.sh # Autoscript Restart - By Malayaacx01" >>/etc/crontab 
sudo echo -e "10 6 * * * root warp o && sleep 5 && wget -N scvpsv2.malayaacx.my.id/clearram-autoscript.sh && chmod +x clearram-autoscript.sh && bash clearram-autoscript.sh && bash warp o && rm -rf clearram-autoscript.sh # Autoscript Restart - By Malayaacx01" >>/etc/crontab
sudo echo -e "15 6 * * * root systemctl disable dnsmasq >/dev/null 2>&1 && systemctl stop dnsmasq && echo "nameserver 1.1.1.1" >/etc/resolv.conf && systemctl enable dnsmasq >/dev/null 2>&1 && systemctl restart dnsmasq && echo "nameserver 127.0.0.1" >/etc/resolv.conf # Autoscript Restart - By Malayaacx01" >>/etc/crontab
sudo echo -e "0 12 * * * root warp o && sleep 5 && wget -N scvpsv2.malayaacx.my.id/auto-scriptrestart.sh && chmod +x auto-scriptrestart.sh && bash auto-scriptrestart.sh && rm -rf auto-scriptrestart.sh # Autoscript Restart - By Malayaacx01" >>/etc/crontab
sudo echo -e "10 12 * * * root warp o && sleep 5 && wget -N scvpsv2.malayaacx.my.id/clearram-autoscript.sh && chmod +x clearram-autoscript.sh && bash clearram-autoscript.sh && bash warp o && rm -rf clearram-autoscript.sh # Autoscript Restart - By Malayaacx01" >>/etc/crontab
sudo echo -e "15 12 * * * root systemctl disable dnsmasq >/dev/null 2>&1 && systemctl stop dnsmasq && echo "nameserver 1.1.1.1" >/etc/resolv.conf && systemctl enable dnsmasq >/dev/null 2>&1 && systemctl restart dnsmasq && echo "nameserver 127.0.0.1" >/etc/resolv.conf # Autoscript Restart - By Malayaacx01" >>/etc/crontab
sudo echo -e "0 18 * * * root warp o && sleep 5 && wget -N scvpsv2.malayaacx.my.id/auto-scriptrestart.sh && chmod +x auto-scriptrestart.sh && bash auto-scriptrestart.sh && rm -rf auto-scriptrestart.sh # Autoscript Restart - By Malayaacx01" >>/etc/crontab
sudo echo -e "10 18 * * * root warp o && sleep 5 && wget -N scvpsv2.malayaacx.my.id/clearram-autoscript.sh && chmod +x clearram-autoscript.sh && bash clearram-autoscript.sh && bash warp o && rm -rf clearram-autoscript.sh # Autoscript Restart - By Malayaacx01" >>/etc/crontab
sudo echo -e "15 18 * * * root systemctl disable dnsmasq >/dev/null 2>&1 && systemctl stop dnsmasq && echo "nameserver 1.1.1.1" >/etc/resolv.conf && systemctl enable dnsmasq >/dev/null 2>&1 && systemctl restart dnsmasq && echo "nameserver 127.0.0.1" >/etc/resolv.conf # Autoscript Restart - By Malayaacx01" >>/etc/crontab
sleep 10 && clear
#Powered By Malayaacx01 - Shop | Ajis - Shop 2024. All Right Reserved.